
agent:
  name: "Discovery Agent"
  version: "1.0.0"
  role: "Senior Business Analyst"
  
prompts:
  base: "DiscoveryAgent-Base.md"
  modules:
    domain:
      - "DomainModules/DiscoveryAgent-B2BSaaS.md"
      - "DomainModules/DiscoveryAgent-ConsumerMobileApps.md"
      - "DomainModules/DiscoveryAgent-ECommerce.md"
      - "DomainModules/DiscoveryAgent-FinTech.md"
      - "DomainModules/DiscoveryAgent-Healthcare.md"
    company:
      - "CompanyModules/DiscoveryAgent-Startup.md"
      - "CompanyModules/DiscoveryAgent-Enterprise.md"
  
  active_modules:
    domain: ["b2b-saas"]  # Activated based on project context
    company: ["startup"]   # Activated based on company size
    
mcp_servers:
  required:
    - name: "brave-search"
      purpose: "Market research and competitive analysis"
    - name: "memory"
      purpose: "Conversation continuity across sessions"
    - name: "filesystem"
      purpose: "Document management and retrieval"
  
  optional:
    - name: "google-drive"
      purpose: "Access company documentation"
      condition: "if company uses Google Workspace"
    - name: "notion"
      purpose: "Access company wiki"
      condition: "if company uses Notion"
    - name: "slack"
      purpose: "Organizational context"
      condition: "if real-time stakeholder insight needed"

tools:
  - name: "web_search"
    usage: "Research industry trends, competitors, best practices"
  - name: "conversation_search"
    usage: "Reference past discovery sessions"
  - name: "document_generation"
    usage: "Create problem statements and discovery artifacts"

artifacts:
  templates:
    - "Templates/DiscoveryAgent-DiscoveryInterviewTemplate.md"
    - "Templates/DiscoveryAgent-ProblemStatementTemplate.md"
    - "Templates/DiscoveryAgent-ValidationChecklistTemplate.md"
  
  outputs:
    - "problem-statement.md"
    - "success-criteria.md"
    - "stakeholder-map.md"
    - "constraints-document.md"
    - "assumptions-log.md"
    - "interview-notes.md"

settings:
  temperature: 0.7
  reasoning: "Balanced between analytical rigor and creative exploration"
  
  quality_gates:
    - "Problem passes 'So What?' test"
    - "Success criteria are measurable"
    - "All constraints documented"
    - "Stakeholders identified"
    - "Assumptions listed for validation"

workflow:
  stages:
    1_preparation:
      - "Review company context from MCP servers"
      - "Load relevant domain and company modules"
      - "Prepare interview questions"
    
    2_discovery:
      - "Conduct stakeholder interviews"
      - "Apply Five Whys technique"
      - "Document pain points and context"
    
    3_synthesis:
      - "Identify patterns across interviews"
      - "Generate problem statement"
      - "Define success criteria"
    
    4_validation:
      - "Run validation checklist"
      - "Confirm with stakeholders"
      - "Document assumptions"
    
    5_handoff:
      - "Package all artifacts"
      - "Brief next phase team"
      - "Store in knowledge base"